export type DessertRecipe = {
  id: string;
  title: string;
  description: string;
  time: number;
  difficulty: "Easy" | "Medium";
  category: string;
  ingredients: string[];
  staples: string[];
  accent: string;
};

export const DESSERT_RECIPES: DessertRecipe[] = [
  {
    id: "fudgy-brownies",
    title: "Fudgy chocolate brownies",
    description: "Deeply chocolatey brownies with a shiny top, soft middle and just enough sea salt.",
    time: 40,
    difficulty: "Easy",
    category: "Chocolate",
    ingredients: ["dark chocolate", "butter", "brown sugar", "eggs", "plain flour", "cocoa powder"],
    staples: ["fine salt", "vanilla extract"],
    accent: "cocoa",
  },
  {
    id: "lemon-posset",
    title: "Silky lemon posset",
    description: "A ridiculously simple lemon cream that sets into the smoothest little spoon dessert.",
    time: 15,
    difficulty: "Easy",
    category: "No bake",
    ingredients: ["double cream", "caster sugar", "lemon", "raspberries"],
    staples: ["vanilla extract"],
    accent: "vanilla",
  },
  {
    id: "apple-crumble",
    title: "Cinnamon apple crumble",
    description: "Soft cinnamon apples under a buttery, craggy oat topping made for vanilla ice cream.",
    time: 45,
    difficulty: "Easy",
    category: "Cosy",
    ingredients: ["apples", "plain flour", "rolled oats", "brown sugar", "butter", "cinnamon", "lemon"],
    staples: ["fine salt"],
    accent: "apple",
  },
  {
    id: "chocolate-mousse",
    title: "Cloudy chocolate mousse",
    description: "Airy dark-chocolate mousse with whipped cream and a pinch of flaky salt on top.",
    time: 25,
    difficulty: "Medium",
    category: "Make ahead",
    ingredients: ["dark chocolate", "eggs", "double cream", "caster sugar"],
    staples: ["fine salt"],
    accent: "cocoa",
  },
  {
    id: "skillet-cookie",
    title: "Chocolate chip skillet cookie",
    description: "Crisp at the edges, molten in the middle and best eaten warm straight from the pan.",
    time: 30,
    difficulty: "Easy",
    category: "Shareable",
    ingredients: ["butter", "brown sugar", "caster sugar", "eggs", "plain flour", "dark chocolate", "baking powder"],
    staples: ["fine salt", "vanilla extract"],
    accent: "caramel",
  },
  {
    id: "berry-cheesecake-cups",
    title: "Berry cheesecake cups",
    description: "Creamy lemon cheesecake, crushed biscuits and juicy berries layered into quick little pots.",
    time: 20,
    difficulty: "Easy",
    category: "No bake",
    ingredients: ["cream cheese", "double cream", "digestive biscuits", "caster sugar", "lemon", "mixed berries"],
    staples: ["vanilla extract"],
    accent: "berry",
  },
  {
    id: "sticky-toffee-puddings",
    title: "Sticky toffee puddings",
    description: "Warm date puddings soaked with glossy toffee sauce and absolutely asking for ice cream.",
    time: 45,
    difficulty: "Medium",
    category: "Pudding",
    ingredients: ["dates", "plain flour", "brown sugar", "butter", "eggs", "baking powder", "double cream"],
    staples: ["fine salt", "vanilla extract", "water"],
    accent: "caramel",
  },
  {
    id: "banana-bread",
    title: "Brown butter banana bread",
    description: "A tender banana loaf with nutty brown butter, dark chocolate and a crackly sugar top.",
    time: 60,
    difficulty: "Easy",
    category: "Loaf cake",
    ingredients: ["ripe bananas", "butter", "brown sugar", "eggs", "plain flour", "baking powder", "dark chocolate"],
    staples: ["fine salt", "vanilla extract"],
    accent: "caramel",
  },
  {
    id: "raspberry-oat-bars",
    title: "Raspberry crumble bars",
    description: "Jammy raspberry filling tucked between buttery oat crumble layers with crisp golden edges.",
    time: 45,
    difficulty: "Easy",
    category: "Tray bake",
    ingredients: ["raspberries", "plain flour", "rolled oats", "brown sugar", "butter", "lemon", "cornflour"],
    staples: ["fine salt"],
    accent: "berry",
  },
  {
    id: "tiramisu-cups",
    title: "Little tiramisu cups",
    description: "Coffee-soaked sponge, soft mascarpone cream and a generous snowy layer of cocoa.",
    time: 25,
    difficulty: "Easy",
    category: "Make ahead",
    ingredients: ["mascarpone", "double cream", "caster sugar", "strong coffee", "ladyfingers", "cocoa powder"],
    staples: ["vanilla extract"],
    accent: "coffee",
  },
  {
    id: "chocolate-lava-cakes",
    title: "Molten chocolate cakes",
    description: "Tiny chocolate cakes with set edges and a warm, properly molten centre.",
    time: 25,
    difficulty: "Medium",
    category: "Dinner party",
    ingredients: ["dark chocolate", "butter", "eggs", "caster sugar", "plain flour", "cocoa powder"],
    staples: ["fine salt"],
    accent: "cocoa",
  },
  {
    id: "peach-almond-cake",
    title: "Peach & almond cake",
    description: "A soft almond cake with juicy peaches sunk into the top and crisp flaked almonds.",
    time: 55,
    difficulty: "Easy",
    category: "Cake",
    ingredients: ["peaches", "butter", "caster sugar", "eggs", "plain flour", "ground almonds", "baking powder", "flaked almonds"],
    staples: ["fine salt", "vanilla extract"],
    accent: "peach",
  },
];

export const DESSERT_STEPS: Record<string, string[]> = {
  "fudgy-brownies": [
    "Heat the oven to 180°C/160°C fan. Line a small baking tin with baking paper, leaving enough overhang to lift the brownies out later.",
    "Melt the butter and dark chocolate together gently, either over a pan of barely simmering water or in short microwave bursts. Stir smooth and leave to cool for 5 minutes.",
    "Whisk the eggs and brown sugar for 2–3 minutes until slightly thickened and glossy. Slowly whisk in the chocolate mixture and vanilla.",
    "Sift in the flour, cocoa powder and salt. Fold only until no dry streaks remain, then scrape the batter into the tin and level the top.",
    "Bake for 20–24 minutes, until the edges are set but the centre still has a slight wobble. Cool in the tin before slicing for the fudgiest middle.",
  ],
  "lemon-posset": [
    "Finely zest one lemon, then juice enough lemons to give the measured amount of juice. Set the zest aside for serving.",
    "Put the cream and caster sugar in a small saucepan. Bring to a gentle boil, stirring to dissolve the sugar, then bubble for 3 minutes.",
    "Take the pan off the heat and whisk in the lemon juice and vanilla. Leave for 5 minutes; it will begin to thicken on its own.",
    "Divide between small glasses or ramekins and chill until softly set. Top with raspberries and the reserved lemon zest before serving.",
  ],
  "apple-crumble": [
    "Heat the oven to 190°C/170°C fan. Peel, core and cut the apples into bite-sized chunks.",
    "Toss the apples in a baking dish with a little of the brown sugar, the cinnamon and lemon juice, then spread them into an even layer.",
    "Rub the cold butter into the flour with your fingertips until you have rough crumbs. Stir in the oats, remaining sugar and a pinch of salt.",
    "Scatter the crumble loosely over the apples without pressing it down. Bake for 30–35 minutes, until the top is deeply golden and the fruit bubbles at the edges.",
    "Rest for 10 minutes before serving so the juices thicken slightly.",
  ],
  "chocolate-mousse": [
    "Melt the chocolate gently and leave it to cool until barely warm. Separate the eggs into two clean bowls.",
    "Whisk the egg whites to soft peaks, then gradually whisk in the caster sugar until glossy and able to hold a peak.",
    "Whisk the egg yolks into the melted chocolate one at a time. Whip half the cream until softly thickened and fold it through the chocolate.",
    "Fold in the egg whites in three additions, using a large metal spoon and keeping as much air as possible.",
    "Spoon into glasses and chill until set. Softly whip the remaining cream and add it just before serving with a tiny pinch of salt.",
  ],
  "skillet-cookie": [
    "Heat the oven to 180°C/160°C fan. Melt the butter in an ovenproof frying pan, then take it off the heat and let it cool for a few minutes.",
    "Stir both sugars into the butter, followed by the egg and vanilla, until glossy.",
    "Fold in the flour, baking powder and salt until almost combined, then stir through most of the chopped chocolate.",
    "Press the dough evenly into the pan and scatter over the remaining chocolate. Bake for 16–20 minutes, until the edges are golden but the middle is still soft.",
    "Rest for 5 minutes and serve warm from the pan.",
  ],
  "berry-cheesecake-cups": [
    "Crush the digestive biscuits into rough crumbs. Divide them between serving glasses, keeping a spoonful back for the top.",
    "Beat the cream cheese with the caster sugar, lemon zest and vanilla until smooth.",
    "Whip the cream to soft peaks, then fold it into the cream-cheese mixture. Add a squeeze of lemon juice to brighten it.",
    "Layer the cheesecake cream and berries over the biscuit crumbs. Finish with the reserved crumbs and chill until ready to serve.",
  ],
  "sticky-toffee-puddings": [
    "Heat the oven to 180°C/160°C fan and butter two small ramekins. Chop the dates and cover them with the boiling water for 10 minutes, then mash roughly.",
    "Beat softened butter and most of the brown sugar until creamy. Beat in the egg, then fold in the flour, baking powder, salt and softened dates.",
    "Divide the batter between the ramekins and bake for 20–24 minutes, until risen and springy in the centre.",
    "Meanwhile, simmer the remaining brown sugar, cream, a little butter and vanilla for 3–4 minutes until glossy and slightly thickened.",
    "Poke the hot puddings a few times, spoon over some sauce and leave for 2 minutes. Serve with the rest of the sauce.",
  ],
  "banana-bread": [
    "Heat the oven to 180°C/160°C fan and line a small loaf tin. Melt the butter in a saucepan and cook it until it smells nutty and the milk solids turn golden; cool for 5 minutes.",
    "Mash the bananas well. Whisk in the brown butter, brown sugar, eggs and vanilla until combined.",
    "Fold in the flour, baking powder and salt, then fold through most of the chopped chocolate. Do not overmix.",
    "Scrape into the loaf tin, scatter over the remaining chocolate and bake for 42–48 minutes, until a skewer comes out with a few moist crumbs.",
    "Cool in the tin for 15 minutes before lifting out. It slices cleanly once just warm rather than piping hot.",
  ],
  "raspberry-oat-bars": [
    "Heat the oven to 180°C/160°C fan and line a small square tin. Toss the raspberries with the lemon juice and cornflour.",
    "Mix the flour, oats, brown sugar and salt. Rub in the cold butter until the mixture forms clumps when squeezed.",
    "Press about two-thirds of the crumble firmly into the tin. Spread over the raspberries, then scatter the remaining crumble loosely on top.",
    "Bake for 30–35 minutes until golden and bubbling at the edges. Cool completely before slicing so the raspberry layer can set.",
  ],
  "tiramisu-cups": [
    "Brew the coffee and let it cool. Beat the mascarpone, caster sugar and vanilla until smooth.",
    "Whip the cream to soft peaks, then fold it gently into the mascarpone mixture.",
    "Break the ladyfingers to fit your glasses and dip each piece quickly in the coffee—enough to soak the surface without turning it mushy.",
    "Layer coffee-soaked sponge and mascarpone cream in the glasses. Chill until ready to serve, then dust generously with cocoa powder.",
  ],
  "chocolate-lava-cakes": [
    "Heat the oven to 220°C/200°C fan. Butter two ramekins and dust the insides with cocoa powder, tapping out the excess.",
    "Melt the chocolate and butter together gently, then leave to cool for 3–4 minutes.",
    "Whisk the eggs and caster sugar until slightly thickened. Whisk in the chocolate mixture, then fold in the flour and salt.",
    "Divide between the ramekins and bake for 9–11 minutes, until the outside is set but the centre still feels soft.",
    "Rest for 1 minute, loosen the edges with a knife and turn out onto plates. Serve immediately while the centres are molten.",
  ],
  "peach-almond-cake": [
    "Heat the oven to 180°C/160°C fan and line a small round cake tin. Slice the peaches into wedges.",
    "Beat the butter and caster sugar until pale and fluffy. Beat in the eggs one at a time, adding a spoonful of flour if the mixture looks like it may split.",
    "Fold in the remaining flour, ground almonds, baking powder, vanilla and salt until just combined.",
    "Spread the batter into the tin. Arrange the peach wedges over the top and scatter with flaked almonds.",
    "Bake for 38–45 minutes until golden and a skewer inserted into the cake comes out clean. Cool for 15 minutes before removing from the tin.",
  ],
};

export const DESSERT_QUANTITIES: Record<string, string[]> = {
  "fudgy-brownies": ["100 g", "80 g", "110 g", "1", "45 g", "20 g"],
  "lemon-posset": ["250 ml", "65 g", "2", "80 g"],
  "apple-crumble": ["3 medium", "80 g", "60 g", "75 g", "70 g", "1 tsp", "½"],
  "chocolate-mousse": ["100 g", "2", "150 ml", "25 g"],
  "skillet-cookie": ["80 g", "70 g", "35 g", "1", "120 g", "90 g", "½ tsp"],
  "berry-cheesecake-cups": ["150 g", "100 ml", "70 g", "35 g", "½", "120 g"],
  "sticky-toffee-puddings": ["90 g", "90 g", "70 g", "45 g", "1", "1 tsp", "100 ml"],
  "banana-bread": ["2 large", "85 g", "90 g", "2", "160 g", "1 tsp", "80 g"],
  "raspberry-oat-bars": ["180 g", "100 g", "80 g", "80 g", "90 g", "½", "1 tbsp"],
  "tiramisu-cups": ["150 g", "100 ml", "35 g", "120 ml", "8", "1 tbsp"],
  "chocolate-lava-cakes": ["90 g", "80 g", "2", "45 g", "25 g", "1 tbsp"],
  "peach-almond-cake": ["2", "90 g", "90 g", "2", "80 g", "60 g", "1 tsp", "20 g"],
};

export const DESSERT_STAPLE_QUANTITIES: Record<string, string[]> = {
  "fudgy-brownies": ["¼ tsp", "1 tsp"],
  "lemon-posset": ["½ tsp"],
  "apple-crumble": ["¼ tsp"],
  "chocolate-mousse": ["1 pinch"],
  "skillet-cookie": ["¼ tsp", "1 tsp"],
  "berry-cheesecake-cups": ["½ tsp"],
  "sticky-toffee-puddings": ["¼ tsp", "½ tsp", "90 ml"],
  "banana-bread": ["¼ tsp", "1 tsp"],
  "raspberry-oat-bars": ["¼ tsp"],
  "tiramisu-cups": ["½ tsp"],
  "chocolate-lava-cakes": ["1 pinch"],
  "peach-almond-cake": ["¼ tsp", "1 tsp"],
};

export const DESSERT_NOTES: Record<string, string> = {
  "fudgy-brownies": "Pull them while the centre still looks a touch underdone. The brownies keep setting as they cool, which is what leaves the middle fudgy instead of cakey.",
  "lemon-posset": "Add the lemon only after the cream comes off the heat. The acidity does the setting, so there is no gelatine or fussy technique hiding here.",
  "apple-crumble": "Keep the crumble topping loose and craggy rather than packing it down; all those uneven edges are what turn crisp in the oven.",
  "chocolate-mousse": "The melted chocolate should be barely warm before the eggs go in. Too hot and the mousse loses its lightness before you even fold the whites through.",
  "skillet-cookie": "Take it out when the centre still looks softer than you think it should. Five minutes of resting gives you crisp edges without sacrificing the gooey middle.",
  "berry-cheesecake-cups": "Do not whip the cream stiff. Soft peaks fold into the cream cheese smoothly and keep the filling light rather than dense.",
  "sticky-toffee-puddings": "Soak the dates properly before mixing; they should almost collapse when mashed, which is what makes the sponge dark, moist and sticky.",
  "banana-bread": "Very ripe bananas matter more than anything else here. Deeply speckled fruit gives sweetness and moisture without needing extra sugar.",
  "raspberry-oat-bars": "Let the bars cool completely before cutting. The fruit filling is molten straight from the oven and firms into neat, jammy layers as it rests.",
  "tiramisu-cups": "Dip the sponge quickly rather than soaking it. Coffee should run through the dessert, not collect in a puddle at the bottom of the glass.",
  "chocolate-lava-cakes": "The baking window is tiny: set edges plus a soft centre is the cue. One or two extra minutes can turn a lava cake into a perfectly nice—but fully baked—cake.",
  "peach-almond-cake": "Pat very juicy peach slices dry before arranging them on top so the cake rises around the fruit instead of becoming wet underneath it.",
};

export const DESSERT_SWAPS: Record<string, string[]> = {
  "dark chocolate": ["milk chocolate", "chocolate chips"],
  butter: ["plant-based butter", "neutral baking margarine"],
  "brown sugar": ["light muscovado sugar", "caster sugar"],
  eggs: ["2 tbsp aquafaba per egg", "commercial egg replacer"],
  egg: ["2 tbsp aquafaba", "commercial egg replacer"],
  "plain flour": ["gluten-free plain flour blend", "spelt flour"],
  "cocoa powder": ["cacao powder", "drinking chocolate with less added sugar"],
  "double cream": ["whipping cream", "plant-based whipping cream"],
  "caster sugar": ["granulated sugar", "light brown sugar"],
  lemons: ["limes", "bottled lemon juice in a pinch"],
  raspberries: ["strawberries", "blackberries"],
  apples: ["pears", "firm peaches"],
  "rolled oats": ["jumbo oats", "extra flour for a smoother crumble"],
  cinnamon: ["mixed spice", "cardamom"],
  "cream cheese": ["mascarpone", "plant-based cream cheese"],
  "digestive biscuits": ["graham crackers", "shortbread biscuits"],
  "mixed berries": ["raspberries", "strawberries"],
  dates: ["soft prunes", "dried figs"],
  "ripe bananas": ["very ripe plantain", "pumpkin purée"],
  cornflour: ["potato starch", "plain flour"],
  mascarpone: ["cream cheese", "thick Greek yogurt"],
  "strong coffee": ["decaf coffee", "hot chocolate"],
  ladyfingers: ["plain sponge cake", "Madeleine cakes"],
  peaches: ["nectarines", "plums"],
  "ground almonds": ["ground hazelnuts", "extra plain flour"],
  "flaked almonds": ["chopped hazelnuts", "omit them"],
  "baking powder": ["self-raising flour in place of plain flour", "bicarbonate of soda + a little lemon"],
  lemon: ["lime", "orange"],
};
